### ISSUE TITLE
Windows: Can't take screenshots or record

### ISSUE THREAD

**Issue by selb** [selb/YumLife#1]
Reported on Discord. User was able to take screenshots / record with OBS both hetuw and the vanilla client. User was not able to do so with YumLife exe. Screenshots/recordings capture whatever is behind the window.

**Comment by selb** [comment]
Next step: rebuild on Ubuntu 14 (as is presumably still used by Jason) to see if my newer mingw is the source of the issue.

**Comment by selb** [comment]
Update: It's clear that nobody's building on Ubuntu 14 anymore, so that's probably (hopefully) not related. I was not able to replicate this in a Windows 11 VM, so I will have to try to replicate on an actual Windows install.

**Comment by MrMendeleev2** [comment]
I reported it in Discord, with newer version it don't seems to be the case.
All good now
![image](https://github.com/selb/YumLife/assets/91346213/3b4c31be-46b8-4232-a2a0-d2c3b33d7e54)

**Comment by selb** [comment]
Great to hear, thanks for the update!
