### ISSUE TITLE
Request For Moderation Change

### ISSUE THREAD

**Issue by Shadie116** [selb/YumLife#24]
Yikes muted me for 24 hours without reason. She does this a lot, just please get better mods.

![image](https://github.com/selb/YumLife/assets/126846097/4e5cf5ba-7ebd-40ba-8b26-88a641bbb85d)

**Comment by selb** [comment]
I don't run phex.

**Comment by ru-the-awakened** [comment]
> Yikes muted me for 24 hours without reason. She does this a lot, just please get better mods.
> 
> ![image](https://user-images.githubusercontent.com/126846097/274980104-4e5cf5ba-7ebd-40ba-8b26-88a641bbb85d.png)

https://www.khanacademy.org/computing/ap-computer-science-principles

Instead of spending all your time trolling github, here's a nice and free set of courses you can take to start learning computer science principles. This will be a much better use of your time and set you up very well for your future as a game developer.

**Comment by Shadie116** [comment]
Game dev, nah computer science. I'm aiming for a network + certification behind my name

**Comment by ru-the-awakened** [comment]
> Game dev, nah computer science. I'm aiming for a network + certification behind my name. I've been reading up on a lot, internet videos and videos won't do nothing for a man. Reading is the best way to educate yourself on an important topic. ![image](https://user-images.githubusercontent.com/126846097/276077049-63e000f9-2167-42a6-88ec-b8b8c5a0498f.png) Infact the very reason I decided to place focus on this is because the great opportunities it could grant me once I'm out of high school and tossed into the business centered economy.
> 
> Anyways please understand what you're talking about in a topic before you say anything you uneducated raw turkey. Please grow the hell up and humble yourself. Talking like you know shit, explain what tcp/ip udp/ osi/ and ip does. I bet you're going to be looking back at this when you're camping out in your car, living life hard because you started too easy. Like god dam, I hate people like you. Acting like you're all powerful when you're just another junky. And you act like I'm rude, I'm only responding back to your rudeness.

That's a nice choice, Shady! I remember when I was studying for Network+, that was such a fun time learning. Pretty easy compared to Security+ though! I can tell you're already quite enamored with the OSI model, I hope you keep up the enthusiasm. Despite both those certificates being entry-level and covering pretty basic knowledge, I recommended the Khan academy courses because it's a pretty good resource that starts out at a College/AP level. That's already super impressive for someone in 6th grade like you, so keep up the great work cowboy. Aren't computers fascinating? You're going to be such a rockstar when you grow up!

**Comment by Shadie116** [comment]
> > Game dev, nah computer science. I'm aiming for a network + certification behind my name. I've been reading up on a lot, internet videos and videos won't do nothing for a man. Reading is the best way to educate yourself on an important topic. ![image](https://user-images.githubusercontent.com/126846097/276077049-63e000f9-2167-42a6-88ec-b8b8c5a0498f.png) Infact the very reason I decided to place focus on this is because the great opportunities it could grant me once I'm out of high school and tossed into the business centered economy.
> > Anyways please understand what you're talking about in a topic before you say anything you uneducated raw turkey. Please grow the hell up and humble yourself. Talking like you know shit, explain what tcp/ip udp/ osi/ and ip does. I bet you're going to be looking back at this when you're camping out in your car, living life hard because you started too easy. Like god dam, I hate people like you. Acting like you're all powerful when you're just another junky. And you act like I'm rude, I'm only responding back to your rudeness.
> 
> That's a nice choice, Shady! I remember when I was studying for Network+, that was such a fun time learning. Pretty easy compared to Security+ though! I can tell you're already quite enamored with the OSI model, I hope you keep up the enthusiasm. Despite both those certificates being entry-level and covering pretty basic knowledge, I recommended the Khan academy courses because it's a pretty good resource that starts out at a College/AP level. That's already super impressive for someone in 6th grade like you, so keep up the great work cowboy. Aren't computers fascinating? You're going to be such a rockstar when you grow up!

I have chosen not to reply to this

**Comment by Shadie116** [comment]
> > Game dev, nah computer science. I'm aiming for a network + certification behind my name. I've been reading up on a lot, internet videos and videos won't do nothing for a man. Reading is the best way to educate yourself on an important topic. ![image](https://user-images.githubusercontent.com/126846097/276077049-63e000f9-2167-42a6-88ec-b8b8c5a0498f.png) Infact the very reason I decided to place focus on this is because the great opportunities it could grant me once I'm out of high school and tossed into the business centered economy.
> > Anyways please understand what you're talking about in a topic before you say anything you uneducated raw turkey. Please grow the hell up and humble yourself. Talking like you know shit, explain what tcp/ip udp/ osi/ and ip does. I bet you're going to be looking back at this when you're camping out in your car, living life hard because you started too easy. Like god dam, I hate people like you. Acting like you're all powerful when you're just another junky. And you act like I'm rude, I'm only responding back to your rudeness.
> 
> That's a nice choice, Shady! I remember when I was studying for Network+, that was such a fun time learning. Pretty easy compared to Security+ though! I can tell you're already quite enamored with the OSI model, I hope you keep up the enthusiasm. Despite both those certificates being entry-level and covering pretty basic knowledge, I recommended the Khan academy courses because it's a pretty good resource that starts out at a College/AP level. That's already super impressive for someone in 6th grade like you, so keep up the great work cowboy. Aren't computers fascinating? You're going to be such a rockstar when you grow up!

wait no nvm I'll explain the osi module through homework pictures. All OSI is is an extended version of tcp with the application split. Now explain to me how to decode an ip to a subnet mask and network id
![image](https://github.com/selb/YumLife/assets/126846097/5d8991cb-7bb2-4c72-8ba3-b39fbdf7ff56)
