### ISSUE TITLE
How did you manage to compile all this?

### ISSUE THREAD

**Issue by RainstormPw** [selb/YumLife#30]
So I was planning on making my own fork of hetuw but found it tedious to figure out how to turn the edited files into an exe like you did. So I was wondering if you could teach me any way to manage it

**Comment by selb** [comment]
Tedium and frustration are characteristic of the software development process. If you expect easy answers and instant gratification, you will fail.

Instead, practice working through issues to the end despite how tedious, frustrating, and unfair it feels. Start small, maybe with an introductory C++ tutorial. Practice again and again, hundreds of times, then thousands. You will learn the technical skills you need, but more importantly you will learn to expect and accept disappointment and how to persevere regardless.

**Comment by RainstormPw** [comment]
Much obliged
