### ISSUE TITLE
Change quit key

### ISSUE THREAD

**Issue by ru-the-awakened** [selb/YumLife#37]
Just a suggestion, but I absolutely despise % as a quit confirmation key. Noone should have to go from clicking a button to putting both their hands on the keyboard and pressing Shift-5 to exit a window. I remember playing a version of hetuw or onelife that had a more sane confirmation key, but can't exactly recall.

**Comment by selb** [comment]
I liked ` for an easy ESC + ` to get out fast, but I figured that some people wouldn't even know where to look for that. So I just made it configurable. :)

https://github.com/selb/YumLife/releases/tag/v406b
