### ISSUE TITLE
Phex names sometimes not visible

### ISSUE THREAD

**Issue by Gfiti** [selb/YumLife#43]
I've had it the following issue a few times the past week.

I greet someone who knows me, and they respond: "Who are you?" -> My Phex name was not visible to them.

Dissconnecting and reconnecting to Phex has solved the Issue each time as far as I can remember. 

Not sure what is causing the issue though.

**Comment by selb** [comment]
9be4db9150649dd1c7096cf023052043a9ea589a has a very good chance of resolving this in the next release.

**Comment by selb** [comment]
I'm 75% sure [v409.4](https://github.com/selb/YumLife/releases/tag/v409.4) fixes this. Or rather, it definitely fixes one cause, but it's not clear that it's the only or primary cause.

**Comment by teliot** [comment]
One issue is that PHEX names are not visible after server crash or restart. This can be fixed on the PHEX server moving forward. But overall the PHEX names showing is one of the more common issues that has already had a few patches making this less frequent. Please continue to report the issue until it is fully resolved, but sadly the PHEX repo is not public just yet.
