### ISSUE TITLE
Scrolling in Phex chat

### ISSUE THREAD

**Issue by DopiePanda** [selb/YumLife#44]
Please, fellow goose enjoyer, let us scroll up and down the Phex chat.
That would be incredible <3

**Comment by selb** [comment]
Yeah, this is definitely something I need to do, particularly for `.list`. The latest release makes the `.list` output significantly smaller, but it is still going to regularly exceed the window height.

**Comment by selb** [comment]
added in 6d84353d1732e8e46fcc3071c1bdc60322057f04 and also released
