### ISSUE TITLE
SDL.dll

### ISSUE THREAD

**Issue by ddzh01** [selb/YumLife#75]
When i'm trying to execute the YumLife exe for Windows, it gives the following error message: "The code execution cannot proceed because SDL.dll was not found. Reinstalling the program maay fix this problem". I reinstalled OHOL but it still shows this error. How do i fix it?

![зображення](https://github.com/selb/YumLife/assets/172981204/c9306dc8-4641-4148-988c-7537e0c43bf8)

**Comment by selb** [comment]
Usually this means you haven't moved YumLife_windows.exe into the OHOL installation directory. Make sure it's in the same folder with the vanilla OneLife.exe and a bunch of folders like settings, graphics, etc.

If it's definitely in the right directory, you may be using a third-party antivirus or "internet security suite" that blocks newly downloaded programs from accessing any files. In that case, you would need to figure out how to add an exception for YumLife_windows.exe in that software.
