### ISSUE TITLE
Use "Services" auth for Phex

### ISSUE THREAD

**Issue by selb** [selb/YumLife#77]
Due to abuse of the third party Phex service, we now need to authenticate Phex users to OHOL accounts so they can be banned properly. I was previously opposed to this because Jason's "Services" authentication system gives the third party service the user's actual email, but I don't have a choice at this point.

The flow for this will need to look like:
- Phex server will send a `JASONAUTH` command with a random challenge string generated by the Phex server
- If the user's email isn't an `@steamgames.com` one, connection will be aborted and a message displayed unless a new `phex_send_email` config option is set
- Otherwise, YumLife will respond with a `JASONAUTH` command with the email and verification hash
- The Phex server will validate the email with Jason's auth server

The Phex server will be responsible for providing appropriate messaging to users of older versions of YumLife that will not respond to the `JASONAUTH` command.

**Comment by teliot** [comment]
beta PHEX server is working with limited testing of phex-jason-auth branch
