### ISSUE TITLE
DonkeyTown and Main Area Families

### ISSUE THREAD

**Issue by DougLefelhocz** [selb/YumLife#79]
A few days ago I saw that there was a Ginger Eve family, after checking things out in the tutorial.  I decided to /die until I got there.  I ended up though playing as one of the children of [Eve Diamond](http://lineage.onehouronelife.com/server.php?action=character_page&id=10737873).  

I don't believe I would /died to go to donkeytown that day if I had known the Diamonds were in Donkeytown.

I also found [a video](https://www.youtube.com/watch?v=UUDNlAe_0EE) which almost looks like someone has /died to donkeytown to become Eve and have children more than once.  

Tarr also made a discord comment about some family being donkeys when there was a racial gap.

It could be useful to people to have some way to tell if a family is in donkeytown or the main area from the upper right hand corner of the screen (or maybe I missed something?).

**Comment by selb** [comment]
I don't believe that there's a way to distinguish from the client side; i.e. the server sends no flag or position that could be used. But the few times I've played lately there has always been an "N word" family in the list, so I'll check again and ask Jason for a DT flag if there's no other solution.
