### ISSUE TITLE
Phex Chat stopped working

### ISSUE THREAD

**Issue by Lokkarius** [selb/YumLife#82]
For 2 days now, whenever I type in Phex chat, it sends back a message "Chat is disabled, will enable later"
It was working fine before.

I think I have the latest version of Yumlife installed; v428.5
As far as I can tell, both OHOL and Steam are up to date.

I apologize if this is not the place for this; I'm new to mods, and PC games in general.
So please explain like I'm 5, how do I fix this issue?

**Comment by selb** [comment]
I don't run the Phex service and am on vacation, so I'm not sure of the specific reason it's disabled at the moment. It's been under persistent attack by an edgy teen who's _really_ obsessed with spamming the N word, so presumably they managed to do that again and the Phex server is closed off until whatever attack they're soi

**Comment by selb** [comment]
(please excuse partial replies, trying to use github on a phone...)

When it comes back up, you probably won't have to do anything.
